### ISSUE TITLE
Prototype variable length keys and values

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#89]
- [ ] `WordRange` -> `ValueRange`
This takes `stack_in: [key.., key_len, num_keys]`.
The keys are lexicographically ordered and the range `key..(key + num_keys)` is read from state.
It returns `stack_out: [mem_address_0, ...mem_address_N]`. 
Each variable sized value is pushed onto the memory.
*Or alternatively*
Doesn't write to memory.
Returns `stack_out: [val_0_0, ...val_0_m, ...val_n_m, stack_index_0, ...stack_index_N]`
`stack_index` counts down from the top of the stack (0 is top of stack).
This way you know any time two `stack_index` are equal then the first value didn't exist in storage. You know the length of the last value as `stack_index_N num_keys sub`.
But this will have to reduce to `[val_0, ...val_m]` by the time the program ends.
- [ ] Memory is no longer `Option<Word>`. Maybe we don't need memory and can just read directly onto the stack? We can return the stack instead of the memory.
- [ ] `pre_slots` and `post_slots` will need to be `[Vec<Word>; num_state_read_programs]` instead of `[Option<Word>; num_state_slots]`. 
- [ ] `StateSlotSlice` -> `[Vec<Word>]`
- [ ] `Access::State`, `Access::StateRange`. These will need to take an extra parameter `index` which is where the word is read from within the `Vec<Word>`
	- [ ] Should `Access::StateRange` fail if it goes outside the inner `Vec<Word>`? Do we need another op that will put multiple slots onto the stack? Seems like we will need a way to get the length of a slot. It might be also pretty useful to have an op that puts an entire slot onto the stack. We would definitely need to be able to get the length in that case.
- [ ] `Access::StateIsSome` -> `Access::StateIsEmpty`. Maybe this isn't even needed
## TODO
- [ ] Need an op to increment a key lexographically.
- [ ] What type is state. Do they have an implicit or explicit length? Do we need a `Access::StateLen`
